# Generated by Django 5.0.1 on 2024-02-10 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='app_food.restaurant'),
        ),
    ]
